/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5RABcYP7dpw
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function Component() {
  return (
    <main className="container mx-auto p-10">
      <section className="mb-10">
        <div className="flex space-x-4 items-center">
          <Avatar className="h-16 w-16">
            <AvatarImage alt="Avatar" src="/profile.jpg" />
            <AvatarFallback>SE</AvatarFallback>
          </Avatar>
          <div>
            <h1 className="text-4xl font-bold">Senior Software Engineer</h1>
            <p className="text-gray-500">Backend Specialist</p>
          </div>
        </div>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">About me</h2>
          </CardHeader>
          <CardContent>
            <p className="text-black-500 mb-4">
              As a backend-focused professional, my expertise lies in building scalable and easy-to-maintain cloud-native software solutions.
            </p>
            <p className="text-black-500 mb-4">
              Adhering to the 'You build it, you run it' philosophy, I ensure top-notch quality and accountability. While possessing a basic understanding of frontend elements, my main strength is in backend engineering, involving designing robust microservices and CI/CD processes.
            </p>
            <p className="text-black-500 mb-4">
              My work has spanned industries, contributing to scalable solutions in Customer Journey and FinTech sectors, with a recent focus on onboarding web2 users into the web3 ecosystem. I also bring leadership experience, guiding small teams in collaborative environments to deliver innovative backend solutions.
            </p>
            <p className="text-black-500 mb-4">
              Grounded in Computer Science and Public Governance, my background integrates technological innovation with strategic planning.
            </p>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Experience</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">Senior Software Engineer, <a href="https://fluidtrends.ch/"><i>FluidTrends</i></a></h3>
                <p className="text-gray-500">2022 - Present</p>
                <p>Working on scalable cloud-native solutions for a product focused on onboarding web2 users into the web3 ecosystem.</p>
                {/* list of highlights */}
                <ul className="list-disc list-inside">
                  <li>Go (Golang), TypeScript</li>
                  <li>Docker, Kubernetes, GCP</li>
                  <li>MongoDB</li>
                  <li>Microservices, gRPC, GraphQL, CI/CD</li>
                  <li>Product, Innovation, Web3</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Senior Software Engineer, <a href="https://around25.com/"><i>Around25</i></a></h3>
                <p className="text-gray-500">2021 - 2023</p>
                <p>Part of a team that delivers scalable microservices-based solutions for a startup focused on Customer Journey experience. Key contributions included the rewritting of NodeJS services in Go (Golang), integrating Keycloak for Authentication and Authorization, System Design around event-based architecture for a better scalability, and delivering new features.</p>
                <ul className="list-disc list-inside">
                  <li>Go (Golang), NodeJS, React</li>
                  <li>Docker, Docker Swarm, Traefik, Kubernetes, GCP, OVH</li>
                  <li>Keycloak, NATS, Redis</li>
                  <li>MySQL, PostgresSQL, MongoDB</li>
                  <li>Microservices, REST APIs, CI/CD</li>
                  <li>SaaS, Customer Journey</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Software Engineer, <a href="https://complyadvantage.com/"><i>ComplyAdvantage</i></a></h3>
                <p className="text-gray-500">2019 - 2021</p>
                <p>Individual contributor alongside the Platform&API team. The team was responsible for delivering APIs and user interfaces used by customers in a collaborative enviroment with DevOps mindset and focus on continuous integration and delivery. Key contributions included breaking down the monolithic application into microservices, implementing OAuth2 authentication and introducing event-driven architecture for scaling purposes. I was involved in all parts of the SDLC, from planning and defining software design documents for new product features to maintenance and scaling.</p>
                <ul className="list-disc list-inside">
                  <li>Python, PHP, Go (Golang), NodeJS</li>
                  <li>Docker, Terraform, Ambassador, Kubernetes, AWS</li>
                  <li>AWS Cognito integration, Kafka, Redis</li>
                  <li>MySQL, MongoDB</li>
                  <li>Microservices, REST APIs, Serverless, CI/CD, E2E Testing, Monitorning & Observability</li>
                  <li>SaaS, FinTech</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Projects</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">Open Source Contribution</h3>
                <p className="text-gray-500">
                  Contributor to the Node.js project, with a focus on improving performance and security.
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Personal Project - API Development</h3>
                <p className="text-gray-500">
                  Developed a REST API for a personal project using Express.js, demonstrating a deep understanding of
                  backend development.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Volunteer Work</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">Coding for Kids, Volunteer Instructor</h3>
                <p className="text-gray-500">
                  Taught basic coding concepts to children in an engaging and interactive way.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Education</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">Bachelor of Science in Computer Science</h3>
                <p className="text-gray-500">XYZ University, 2012 - 2016</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Awards</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">Best Developer, XYZ Corp</h3>
                <p className="text-gray-500">Awarded for exceptional performance and contributions to the team.</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Languages</h2>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold">English</h3>
                <p className="text-gray-500">Native Proficiency</p>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Spanish</h3>
                <p className="text-gray-500">Professional Working Proficiency</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>
      <section className="mb-10">
        <Card>
          <CardHeader>
            <h2 className="text-2xl font-bold">Contact Information</h2>
          </CardHeader>
          <CardContent>
            <p>
              Email:{" "}
              <Link className="text-blue-500 underline" href="#">
                example@example.com
              </Link>
            </p>
            <p>
              LinkedIn:{" "}
              <Link className="text-blue-500 underline" href="#">
                linkedin.com/in/example
              </Link>
            </p>
            <p>
              Github:{" "}
              <Link className="text-blue-500 underline" href="#">
                github.com/example
              </Link>
            </p>
          </CardContent>
        </Card>
      </section>
    </main >
  )
}
