name: generate-index

on:
  push:
    branches:
      - master
    paths:
      - resume.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/npm@master

    - name: Install jsonresume and generate
      run: |
        npm install resume-cli
        npm install jsonresume-theme-classy
        ./node_modules/.bin/resume export index.html --theme classy
